export const constantRoutes=[
    {
        path:"/login",
        component:()=>import ("@/views/login/index.vue"),
        name:"login",
        meta:{
            title:"登录",
            hidden:true,
            icon:"Promotion"
        }
    },
    {
        path:"/",
        component:()=>import ("@/layout/index.vue"),
        name:"layout",
        redirect:"/home",
        meta:{
            title:"",
            hidden:false,
            icon:""
        },
        children:[
            {
                path:"/home",
                component:()=>import ("@/views/home/index.vue"),
                meta:{
                    title:"首页",
                    hidden:false,
                    icon:"HomeFilled"
                }
            }
        ]
    },
    {
        path:"/screen",
        component:()=>import("@/views/screen/index.vue"),
        name:"Screen",
        meta:{
            title:"大屏可视化",
            icon:"Monitor"
        }
    },
    {
        path:"/acl",
        component:()=>import("@/layout/index.vue"),
        name:"Acl",
        meta:{
            title:"权限管理",
            icon:"Lock"
        },
        redirect:"/acl/user",
        children:[
            {
                path:"/acl/user",
                component:()=>import("@/views/acl/user/index.vue"),
                name:"user",
                meta:{
                    title:"用户管理",
                    icon:"User"
                }
            },
            {
                path:"/acl/role",
                component:()=>import("@/views/acl/role/index.vue"),
                name:"Role",
                meta:{
                    title:"角色管理",
                    icon:"UserFilled"
                }
            },
            {
                path:"/acl/permission",
                component:()=>import("@/views/acl/permission/index.vue"),
                name:"Permission",
                meta:{
                    title:"菜单管理",
                    icon:"HelpFilled"
                }
            }
        ]
    },
    {
        path:"/product",
        component:()=>import("@/layout/index.vue"),
        name:"Product",
        meta:{
            title:"商品管理",
            icon:"Goods"
        },
        redirect:'/product/attr',
        children:[
            {
                path:'/product/attr',
                component:()=>import("@/views/product/attr/index.vue"),
                name:"Attr",
                meta:{
                    title:"属性管理",
                    icon:"Document"
                }
            },
            {
                path:'/product/sku',
                component:()=>import("@/views/product/sku/index.vue"),
                name:"Sku",
                meta:{
                    title:"Sku管理",
                    icon:"Orange"
                }
            },
            {
                path:'/product/spu',
                component:()=>import("@/views/product/spu/index.vue"),
                name:"Spu",
                meta:{
                    title:"Spu管理",
                    icon:"Apple"
                }
            },
            {
                path:'/product/trademark',
                component:()=>import("@/views/product/trademark/index.vue"),
                name:"Trademark",
                meta:{
                    title:"品牌管理",
                    icon:"GoldMedal"
                }
            },
        ]
    },
    {
        path:"/404",
        component:()=>import ("@/views/404/index.vue"),
        name:"404",
        meta:{
            title:"404",
            hidden:true,
            icon:"ChatRound"
        }
    },
    {
        path:"/:pathMatch(.*)*",
        redirect:"/404",
        name:"Any",
        meta:{
            title:"任意路由",
            hidden:true,
            icon:"Position"
        }
    }
]